"""
dashboard_router.py – Phase 15 (Final – Weekly + Monthly)
────────────────────────────────────────────
Handles admin dashboard summaries received from Google Apps Script.

Endpoints:
 • /dashboard/weekly-summary   – triggered by GAS weekly time-based job
 • /dashboard/monthly-summary  – triggered by GAS monthly time-based job

Notes:
 • No CRON jobs run on Render. All time-based summaries are
   executed by Google Apps Script and POSTed to these endpoints.
 • Messages are sent via the approved WhatsApp template:
   'admin_generic_alert_us'.
────────────────────────────────────────────
"""

import os
import logging
from flask import Blueprint, request, jsonify
from .utils import send_whatsapp_template

bp = Blueprint("dashboard_bp", __name__)
log = logging.getLogger(__name__)

# ──────────────────────────────────────────────
# Environment variables
# ──────────────────────────────────────────────
NADINE_WA = os.getenv("NADINE_WA", "")
TPL_ADMIN_ALERT = "admin_generic_alert_us"
DEFAULT_LANG = os.getenv("TEMPLATE_LANG", "en_US")


# ──────────────────────────────────────────────
# Weekly Summary (GAS → Render webhook)
# ──────────────────────────────────────────────
@bp.route("/weekly-summary", methods=["POST"])
def weekly_summary():
    """
    Handles weekly studio performance summaries generated
    by the Google Apps Script trigger.
    """
    try:
        data = request.get_json(force=True)
        revenue = float(data.get("revenue", 0))
        attendance = str(data.get("attendance", "0"))
        outstanding = float(data.get("outstanding", 0))
        count = int(data.get("outstanding_count", 0))
        chart = data.get("chart_url", "").strip()

        summary_text = (
            f"PilatesHQ Weekly: Revenue R{revenue:,.0f}, "
            f"Attendance {attendance}%, "
            f"Outstanding {count} (R{outstanding:,.0f}). "
            f"Chart: {chart}"
        )

        send_whatsapp_template(NADINE_WA, TPL_ADMIN_ALERT, DEFAULT_LANG, [summary_text])
        log.info("✅ Weekly dashboard summary sent.")
        return jsonify({"ok": True, "message": "Weekly summary sent"})
    except Exception as e:
        log.error(f"❌ Weekly dashboard error: {e}")
        return jsonify({"ok": False, "error": str(e)}), 500


# ──────────────────────────────────────────────
# Monthly Summary (GAS → Render webhook)
# ──────────────────────────────────────────────
@bp.route("/monthly-summary", methods=["POST"])
def monthly_summary():
    """
    Handles monthly financial and attendance summaries
    generated by the Google Apps Script trigger.
    """
    try:
        data = request.get_json(force=True)
        month_label = data.get("month_label", "")
        revenue = float(data.get("revenue", 0))
        outstanding = float(data.get("outstanding", 0))
        mom_change = float(data.get("mom_change", 0))
        top_debtors = data.get("top_debtors", [])  # [{name, amount}]
        chart = data.get("chart_url", "").strip()

        # Build compact template-safe text (single line)
        debt_txt = ""
        if top_debtors:
            parts = [f"{d.get('name','?')} R{float(d.get('amount',0)):.0f}" for d in top_debtors]
            debt_txt = " | Debtors: " + "; ".join(parts)

        msg = (
            f"PilatesHQ {month_label} Snapshot: "
            f"Revenue R{revenue:,.0f} ({mom_change:+.1f}% MoM), "
            f"Outstanding R{outstanding:,.0f}{debt_txt}. "
            f"Chart: {chart}"
        )

        send_whatsapp_template(NADINE_WA, TPL_ADMIN_ALERT, DEFAULT_LANG, [msg])
        log.info("✅ Monthly dashboard summary sent.")
        return jsonify({"ok": True, "message": "Monthly summary sent"})
    except Exception as e:
        log.error(f"❌ Monthly dashboard error: {e}")
        return jsonify({"ok": False, "error": str(e)}), 500
